# Generated by Django 4.1.7 on 2023-02-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
