# Generated by Django 4.1.7 on 2023-02-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_product_cat_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bookdate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='booking_end',
        ),
        migrations.AddField(
            model_name='product',
            name='product_desc',
            field=models.TextField(default=' ', max_length=200),
        ),
        migrations.CreateModel(
            name='ProdBookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookdate', models.DateTimeField(auto_now=True)),
                ('booking_end', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
