# Generated by Django 4.1.7 on 2023-02-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_product_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodbookingdetails',
            name='bookdate',
            field=models.DateTimeField(),
        ),
    ]
